compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/transformer-js@*":
    dependencies:
      "@parcel/core": "*"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
